//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace DotNetTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public Nullable<int> users_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        [Display(Name ="Điểm số")]
        public int scores { get; set; }
        [Display(Name ="Ngày làm bài")]
        public Nullable<System.DateTime> submited_date { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual user user { get; set; }
    }
}
