//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace DotNetTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.exams = new HashSet<exam>();
            this.scores = new HashSet<score>();
        }
    
        public int id { get; set; }
        [Display(Name ="người dùng")]
        public string username { get; set; }
        [Display(Name ="Mật khẩu")]
        public string Password { get; set; }
        [Display(Name ="Họ")]
        public string first_name { get; set; }
        [Display(Name ="Tên")]
        public string last_name { get; set; }
        [Display(Name ="Email")]
        public string Email { get; set; }
        [Display(Name ="Số điện thoại")]
        public string phone { get; set; }
        [Display(Name ="Ngày sinh")]
        public Nullable<System.DateTime> birthday { get; set; }
        [Display(Name ="Giới tính")]
        public string gender { get; set; }
        [Display(Name ="MSSV")]
        public string student_number { get; set; }
        [Display(Name ="Ảnh đại diện")]
        public string avatar { get; set; }
        [Display(Name ="Quyền truy cập")]
        public string role_name { get; set; }
        [Display(Name ="Trạng thái")]
        public byte active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam> exams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<score> scores { get; set; }
    }
}
